version: '3.9'

services:

  http:
    container_name: http_server_v2
    image: http_server:2.0
    build:
      context: .
      dockerfile: Dockerfile
      target: http_server
    ports:
      - 8080:8080
    networks:
      - services_network_v2
    depends_on:
      - user
    environment:
      - USER_SERVER=user
      - USER_PORT=50051
      - DETAILS_SERVER=details
      - DETAILS_PORT=50051


  user:
    container_name: user_server_v2
    image: user_server:2.0
    build:
      context: .
      dockerfile: Dockerfile
      target: grpc_user_server
    expose:
      - 50051
    networks:
      - services_network_v2
      - mysql_network_v2
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_NAME=grpc_user
      - DB_USER=admin
      - DB_PASSWORD=password


  mysqldb:
    image: mysql
    container_name: mysqldb_server_v2
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=grpc_user
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_db_v2:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network_v2


volumes:
  mysql_db_v2:
    name: mysql_v2


networks:
  services_network_v2:
    driver: bridge
    name: services_v2
  mysql_network_v2:
    driver: bridge
    name: mysql_v2