version: '3.9'

services:

  http:
    container_name: http_server_v1
    image: http_server:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: http_server
    ports:
      - 8080:8080
    networks:
      - services_network_v1
    depends_on:
      - user
      - details
    environment:
      - USER_SERVER=user
      - USER_PORT=50051
      - DETAILS_SERVER=details
      - DETAILS_PORT=50051


  user:
    container_name: user_server_v1
    image: user_server:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: grpc_user_server
    expose:
      - 50051
    networks:
      - services_network_v1
      - mysql_network_v1
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_NAME=grpc_user
      - DB_USER=admin
      - DB_PASSWORD=password


  details:
    container_name: details_server_v1
    image: details_server:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: grpc_details_server
    expose:
      - 50051
    networks:
      - services_network_v1
      - mongo_network_v1
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=grpc_details
      - DB_USER=admin
      - DB_PASSWORD=password


  mongodb:
    image: mongo
    container_name: mongodb_server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=grpc_details
    volumes:
      - mongo_db_v1:/data/db
    networks:
      - mongo_network_v1


  mysqldb:
    image: mysql
    container_name: mysqldb_server
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=grpc_user
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_db_v1:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network_v1


volumes:
  mysql_db_v1:
    name: mysql_v1
  mongo_db_v1:
    name: mongo_v1


networks:
  services_network_v1:
    driver: bridge
    name: services_v1
  mongo_network_v1:
    driver: bridge
    name: mongo_v1
  mysql_network_v1:
    driver: bridge
    name: mysql_v1